### ISSUE TITLE
Harmonic Magnetic Dipole

### ISSUE THREAD

**Issue by lheagy** [ubcgif/em#134]
Content for [frequency domain magnetic dipole](http://em.geosci.xyz/content/maxwell1_fundamentals/maxwells_equations/maxwells_equations_in_homogeneous_media/frequency_domain/dipole_sources/magnetic_dipole/index.html)

Pages that need to be filled in: 
- [x] index
- [x] what_is_it
- [x] analytic_solution
- [x] vector_potential
- [x] fields
- [x] asymptotics
- [x] field_transformations
- [x] app 

Located in 
```
maxwell1_fundamentals/
   maxwells_equations/
      maxwells_equations_in_homogeneous_media/
         frequency_domain/
            dipole_sources/
              magnetic_dipole/
```

See attached notes: 
 - [harmonic_magnetic_dipole.pdf](https://github.com/ubcgif/em/files/266795/harmonic_magnetic_dipole.pdf)

**Comment by sgkang** [comment]
First path is done.
