### ISSUE TITLE
Transient Electric Dipole

### ISSUE THREAD

**Issue by lheagy** [ubcgif/em#135]
Content for [time domain electric dipole](http://em.geosci.xyz/content/maxwell1_fundamentals/maxwells_equations/maxwells_equations_in_homogeneous_media/time_domain/dipole_sources/electric_dipole/index.html)

Pages that need to be filled in: 
- [x] index
- [x] what_is_it
- [x] analytic_solution
- [x] vector_potential
- [x] fields
- [x] asymptotics
- [x] field_transformations
- [x] app

Located in 
```
maxwell1_fundamentals/
   maxwells_equations/
      maxwells_equations_in_homogeneous_media/
         time_domain/
            dipole_sources/
              electric_dipole/
```

See attached notes: 
 - [transient_electric_dipole.pdf](https://github.com/ubcgif/em/files/266799/transient_electric_dipole.pdf)

**Comment by sgkang** [comment]
First path is done
