### ISSUE TITLE
Transient Magnetic Dipole

### ISSUE THREAD

**Issue by lheagy** [ubcgif/em#136]
Content for [time domain magnetic dipole](http://em.geosci.xyz/content/maxwell1_fundamentals/maxwells_equations/maxwells_equations_in_homogeneous_media/time_domain/dipole_sources/magnetic_dipole/index.html)

Pages that need to be filled in: 
- [ ] index
- [ ] what_is_it
- [ ] analytic_solution
- [ ] vector_potential
- [ ] fields
- [ ] asymptotics
- [ ] field_transformations

Located in 
```
maxwell1_fundamentals/
   maxwells_equations/
      maxwells_equations_in_homogeneous_media/
         time_domain/
            dipole_sources/
              magnetic_dipole/
```

See attached notes: 
- [transient_magnetic_dipole.pdf](https://github.com/ubcgif/em/files/266800/transient_magnetic_dipole.pdf)

**Comment by sgkang** [comment]
@dccowan did.
