### ISSUE TITLE
Online Binders are broken: SimPeG.Examples not found

### ISSUE THREAD

**Issue by thast** [ubcgif/em#159]
![screenshot 2016-06-16 16 33 23](https://cloud.githubusercontent.com/assets/13682747/16136537/265e7f78-33e0-11e6-981e-eae0a0ffe148.png)

**Comment by lheagy** [comment]
this is because sphereElectrostatic_example is not in base SimPEG (as we talked about in simpeg/simpeg#249). The sphereElectrostatic_example.py should be included and imported as a code in https://github.com/ubcgif/em_examples/tree/master/util_codes.

**Comment by lheagy** [comment]
This is covered in the em_examples repository: ubcgif/em_examples#6
