### ISSUE TITLE
MIM figures

### ISSUE THREAD

**Issue by lheagy** [ubcgif/em#164]
if it is easy to re-create, there are a couple figures with overlapping text and colorbars. This can be solved with `plt.tight_layout()` at the end of the plotting instructions in python 
![survey em geosci 2016-06-26 14-41-36](https://cloud.githubusercontent.com/assets/6361812/16365145/56f74ec0-3bac-11e6-96b7-d093016b3a75.png)
- [x] figure 84 http://em.geosci.xyz/content/case_histories/mt_isa/survey.html
- [x] figure 85 http://em.geosci.xyz/content/case_histories/mt_isa/survey.html
- [x] table 4 http://em.geosci.xyz/content/case_histories/mt_isa/processing.html
- [x] table 6 http://em.geosci.xyz/content/case_histories/mt_isa/processing.html

![processing em geosci 2016-06-26 14-47-06](https://cloud.githubusercontent.com/assets/6361812/16365172/e64eda02-3bac-11e6-901e-02a3e40a66b9.png)

**Comment by fourndo** [comment]
Resolved in PR #294
