### ISSUE TITLE
MIM surveys

### ISSUE THREAD

**Issue by dougoldenburg** [ubcgif/em#173]
http://em.geosci.xyz/content/case_histories/mt_isa/survey.html

(a) As much as I like charges, I think they don’t help here. I’d recommend removing them and having some light lines in background to indicate geometry.  

(b) Also, the attempt to have variable thickness of lines for current density is a good idea but I suggest we just keep to uniform lines. I think less is more and the important thing we want to highlight is the changes of directions.

**Comment by fourndo** [comment]
Regarding (a), can we just put conductivity in the background. Creating lines is actually a lot of work as it needs to be done manually.
