### ISSUE TITLE
MIM #3 Interpretation

### ISSUE THREAD

**Issue by dougoldenburg** [ubcgif/em#178]
I'd recommend the following:

Interpretation:

In this section, we interpet  the physica property models recovered through inversion, in terms of geologic units. The basis of our interpretations comes from the physical properties table (?link?)  and the geologic model (?reproduce here). The cross-section is most appropriate for  N12200.  We also provide two plan view sections (depth??) {Fig 110} that aid the discussion.

The animations for conductivity and chargeabilty can be viewed {link} and  iso-surface images are provided in Fig 109. On those images we have also indicated some features or regions  that can be discussed in our interpretation.

A: Eastern Creek Volcanics: The region is resistive and non-chargeable. It appears as a steeply dipping contact with the adjacent siltstones. 

B: The predominant rocks in this region are the Moondara and Native Bee Siltstones. They cannot be distinguished on the basis of conductivity and chargeabilty. The easternly located Moondara rocks may be separated from the Native Bee siltstones by the Eastern Creek volcanics which is a quartzite unit. This should be resistive and non-chargeable. There is some indication that we may be seeing the sequency of “Moondarra siltstone – Eastern Creek Volcanics – Native Bee” in the southern part of the inversion, near 12200 where the cross-section is situated. However, as we proceed north, the resistor disappears and so does any way of separating Moondarra and Native Bee rocks.

C: Breakaway Shales: This is a highly conductive unit that dominates the conductivity model.  Conductivities in the inversion exceeded 10 S/m. The black line D, which denotes the horiontal location of the near surface portion of the unit, will be used in other images.  We note that the shale unit does not appear to be chargeable. This is more evident in the  planview section in Fig 110b. The trace of the high conductivity is associated with chargeabilty lows.

E,F: Mt. Novit Horizon:  This is characterized by a zone of moderately high conductivity and high chargeabilty. The line E has been drawn to reflect that correlation and it corresponds to a similar trajectory presented in the initial paper by Rutley. The chargeability along this trajectory is not uniform. There is variation in amplitude and breakages. 

G:  Other regions of chargeabilty, and potentially minerization, within the siltstone complex. Much of this seems to be “in-board”  (west) of the Breakaway shale. 

Summary

The inversion has imaged, in 3D, the highly conductive Breakaway Shale unit, the western boundary of the siltstones that host the mineralization, a linear moderately conductive and chargeable feature identified as the Mt Norvit Horizon, and chargeable regions of moderate conductivity between the Mt. Norvit Horizon and the Breakaway shales. 

Comment: I’d recommend leaving Fig 111 out of this part and ending it with above positive statements rather than ending with statements concerning artifacts and lack of resolution.

**Comment by lheagy** [comment]
this is supposed to be content.

**Comment by krisdavis** [comment]
Taken care of in MIM_DF_edits branch.
