### ISSUE TITLE
MIM #4 Setup

### ISSUE THREAD

**Issue by dougoldenburg** [ubcgif/em#179]
the Setup should explicitly outline the questions to be addressed. I suggest that we include the following:

Questions to be addressed.

	Two primary questions that motivated the initial study were:
(1) Can geophysical data and 3D inversion delineate the various units shown in the geologic section?

(2) Can conductive and chargeable units within the silstones, be identified. These would be potential targets for mineralization.

	In addition we have an opportunity to re-invert the same data as Rutley et al but use improved algorithms and higher performance computers. Thus
(3) Are improved results obtained by using updated algorithms and higher performance computers?

(4) Are there any  lessons worth highlighting that arose within this case history that were not delineated in the initial case history paper.

**Comment by krisdavis** [comment]
Taken care of in MIM_DF_edits branch.
