### ISSUE TITLE
MIM #5 Synthesis

### ISSUE THREAD

**Issue by dougoldenburg** [ubcgif/em#180]
Can this be re-written so that we address the questions raised in the setup? I've outline material below. 
The questions were:

Questions to be addressed.

Two primary questions that motivated the initial study were:
(1) Can geophysical data and 3D inversion delineate the various units shown in the geologic section?

(2) Can conductive and chargeable units within the silstones, be identified. These would be potential targets for mineralization.

These questions have been addressed in the interpretation section. We could repeat the two volume images Fig 109 and annotate with a few extra geologic units and some prospective targets. 

In addition we have an opportunity to re-invert the same data as Rutley et al but use improved algorithms and higher performance computers. Thus
(3) Are improved results obtained by using updated algorithms and higher performance computers?

(4) Are there any  lessons worth highlighting that arose within this case history that were not delineated in the initial case history paper.

**Comment by dougoldenburg** [comment]
.. something happened and I can't add extra text.

For question 3: Merge material that you have with respect to cell size and higher resolution. I still find the final cross-section with inversion results very complicated. Could this be simplified by breaking it into two panels? one with conductivity and the other with chargeability? 

For question 4:  This can be a lead-in to the problem with the conductor on the outer boundary of the data area. 
      I agree that there is a difference between the 2D and 3D results but I don't think it has a high enough impact to elevate it to a special lesson. Perhaps the major outcome of this can be inlcuded in the answer for question 3, and we just mention that 3D becomes important when there are breaks or changes in a predominantly 2D structure (as observed in the Mt Novit horizon)

**Comment by krisdavis** [comment]
Taken care of in MIM_DF_edits branch.
