### ISSUE TITLE
MIM intepretation

### ISSUE THREAD

**Issue by dougoldenburg** [ubcgif/em#187]
The last paragraph of Summary almost seems redundant. For the enhanced inversion can some extra use be made of the geologic cross-section and the results at the southern end. Incorporating the iso-surfaces did not work out too well, but maybe there is something that could be done.

**Comment by fourndo** [comment]
@krisdavis : Did you take care of that? Or is it on my to-do?

**Comment by krisdavis** [comment]
I'm closing this issue as it will be taken care of in the MIMinterp pull request.
