### ISSUE TITLE
Geophysical surveys layout

### ISSUE THREAD

**Issue by dougoldenburg** [ubcgif/em#202]
We need a consistent layout for the surveys. I think we are little pedantic about the Tx, Rx, Systems. They could be included under a single heading of Instrumentation.  How about the following format?

DCR (or any survey)

Landing page:   iconic image for DCR
    Motivational examples
Basic ideas 
Examples:  (links to case histories that use the technique)
Governing equations
Instrumentation    (includes Tx, Rx, Systems)
Survey design
Data 
Interpretation
Practical Considerations

**Comment by lheagy** [comment]
What do you envision as the difference between the "Motivational Examples" and "Examples"? From a user perspective, I think having a single "Examples" page, with motivational examples, and further link to case histories might be the way to go?

**Comment by lheagy** [comment]
What about combining "Governing Equations" and "Basic Ideas" into a single "Governing Physics" (the equations are then more tightly coupled to the basic ideas)?

**Comment by lheagy** [comment]
- [ ] index page (landing page):
     - purpose (motivation, why) (eg. Purpose: to illustrate the fundamentals of a DC resistivity survey, provide a vision for how it is applied in the field, and demonstrate potential uses) 
     - iconic image (shows the basics, fundamentals, eg. DC one right now)
     - motivational examples to show where it has been useful (these contain links to case histories)
     - overview of the chapter: what (v. similar to what is currently there) 
     - contents | case histories (lists of both)
- [ ] physics 
    - start with iconic picture(s) (Figure 2 on http://gpg.geosci.xyz/en/latest/content/DC_resistivity/DC_measurements_and_data.html)
    -  once over lightly 
    - bring in 2 sphere example
        - charges + currents (movie)
        - potentials 
   - governing equations: formulate in terms of j, phi (link back to fundamentals). Pictures connected to each of the variables in the equations (show potential and highlight phi, for example)
- [ ] survey 
    - setup: basic survey - 4 electrode system (transmitter and receiver - link to instrumentation). Can put in any configuration (eg. poles, dipoles)  - link to survey design (prompt that you should give thought to line spacing, station spacing, ...) 
   - layout: wenner, slb, ..., "rules of thumbs" (electrode spacing, depth of investigation) 
   - instrumentation: transmitters, receivers, systems
- [ ] data:
    - plotting data (pseudo-sections)
    - apparent resistivity - why would you plot these? what do you gain?  
- [ ] interpretation: 
    - inversion 
    - depth of investigation
    - hypothesis testing   
- [ ] survey design: working with synthetics - forward and inverse 
- [ ] practical considerations: 

Index page layout
![image](https://cloud.githubusercontent.com/assets/6361812/17415357/60bd765e-5a3e-11e6-84ad-a85564553c51.png)

**Comment by fourndo** [comment]
looking sharp.
How do you split the page in two (i.e. drawing)?
Can you push an example in rst?

**Comment by lheagy** [comment]
(don't actually know yet, ha). I can take a first crack at the re-organization and then do a pr to run it by everyone?

**Comment by lheagy** [comment]
This issue will be addressed in 
- index: #204,  
- physics: #205
- survey #206
- data #207
- interpretation #208
- survey design #209
- practical considerations #210
