### ISSUE TITLE
DCR Survey Page 

### ISSUE THREAD

**Issue by lheagy** [ubcgif/em#206]
http://em.geosci.xyz/content/geophysical_surveys/dcr/survey.html

- [x] purpose
- [x] basic setup: 4 electrode system: 2 electrodes used to compose a transmitter, 2 a receiver. Can be put in a variety of configurations (image with each: could use -http://gpg.geosci.xyz/en/latest/content/DC_resistivity/DC_measurements_and_data.html) 
    - [x] dipole-dipole
    - [x] pole-dipole
    - [x] dipole-pole
    - [x] pole-pole
- [x] layouts
    - [ ] wenner, schlumberger, gradient array ...
    - [ ] "rules of thumb" (eg. electrode spacing connection with depth of investigation)
- [x] instrumentation 

This will address point 3 of #202

**Comment by sdevriese** [comment]
I think this can be closed?

**Comment by lheagy** [comment]
sounds good @sdevriese. I will let you close this. Could you please reference the pr where it was addressed. Thanks!

**Comment by sdevriese** [comment]
PR #233 
The branch was called DCRsurveysSD
