### ISSUE TITLE
DCR data page

### ISSUE THREAD

**Issue by lheagy** [ubcgif/em#207]
http://em.geosci.xyz/content/geophysical_surveys/dcr/data.html

- [x] purpose 
- [x] plotting data as pseudo sections
    - [x] can we turn the gifs to movies that we can pause ( @fourndo ??)
- [x] apparent resistivity 
    - [x] what is apparent resistivity
    - [x] why plot it?

This addresses point 4 on #202

**Comment by sdevriese** [comment]
Mike's branch was merged into Dom's (PR #264).
