### ISSUE TITLE
DCR interpretation page

### ISSUE THREAD

**Issue by lheagy** [ubcgif/em#208]
http://em.geosci.xyz/content/geophysical_surveys/dcr/interpretation.html
- [ ] purpose
- [ ] inversion: light overview of inversion used - general procedure, citations of Doug and Yaoguo's tutorial, links to SimPEG as appropriate
- [ ] depth of investigation
- [ ] hypothesis testing

This addresses point 5 of #202

**Comment by sdevriese** [comment]
@fourndo If all this is done (and probably is, right, given the work from last week?), can you close this issue? Thanks!
