### ISSUE TITLE
DCR Survey

### ISSUE THREAD

**Issue by dougoldenburg** [ubcgif/em#222]
I suggest altering this section as per the attached page. 
[DCR_Survey.pdf](https://github.com/ubcgif/em/files/417188/DCR_Survey.pdf)

**Comment by sdevriese** [comment]
On it.

**Comment by sdevriese** [comment]
Changes have been pushed on branch "DCRsurveySD" and ready for comments. Thanks!

**Comment by sdevriese** [comment]
PR #233
