### ISSUE TITLE
DCR Data

### ISSUE THREAD

**Issue by dougoldenburg** [ubcgif/em#223]
I suggest altering this section as per the attached page. 
For this section and for the Survey, there is material in the GPG which is instructive. I suggest putting the material we want into EM.geosci and then deciding later if we want figures/equations shared.

[DCR_Data.docx](https://github.com/ubcgif/em/files/417221/DCR_Data.docx)

**Comment by fourndo** [comment]
Taking this one.

**Comment by lheagy** [comment]
The animations were pulled in in #228 (onto master). There are 3 of them outlined in the pull request. They are included in the website using for example. 
```
.. raw:: html
    :file: images/sounding_radio_buttons.html
``` 
Have a look when you get a chance and let me know if anything is unclear!

**Comment by micmitch** [comment]
Switched with Dom. My rework of this page is on the DC_Data branch. Thanks for sorting out the animations Lindsey.

**Comment by micmitch** [comment]
Pretty sure all this was done a week or so ago....
