### ISSUE TITLE
Orphaned pages

### ISSUE THREAD

**Issue by lheagy** [ubcgif/em#26]
The pages 
- formative_laws_and_people/ampere
- formative_laws_and_people/conservation_of_charge

do not appear in any toc tree. Has the content been moved into / combined into another page? Should we remove them?

**Comment by lheagy** [comment]
any objections if these pages are deleted from the repository? is there any content that should be moved or appended to the ampere, conservation of charge pages that are in fundamental laws?

I believe @thast , @sgkang made these initial pages??

**Comment by thast** [comment]
I think @mikemcm did the Ampere page.

No objection otherwise.

**Comment by mikemcm** [comment]
nope, not my page, but I'm happy if you delete it!

Cheers,

Mike

**Comment by mikemcm** [comment]
Nope that's not my page, but I'm one

**Comment by sgkang** [comment]
ha. Yes, I made conservation of charge. Feel free to remove.

**Comment by lheagy** [comment]
closed with #54
