### ISSUE TITLE
Naming issue Fig. 63: dipole-dipole or gradient or ...

### ISSUE THREAD

**Issue by yangdikun** [ubcgif/em#260]
Not sure if the config in Fig. 63 should be called dipole-dipole. To me it looks like either a gradient or Schlumberger. 

![dipole-dipole](https://cloud.githubusercontent.com/assets/5066933/17952607/0f675c14-6a21-11e6-949a-a2b1fba8e6c0.PNG)

**Comment by sdevriese** [comment]
It is a Schlumberger. Doug brought that up too and @micmitch has fixed it but not sure if that fix is now on master yet

**Comment by sdevriese** [comment]
This has now been fixed. Pull request #281
