### ISSUE TITLE
DCR Interpretation

### ISSUE THREAD

**Issue by dougoldenburg** [ubcgif/em#267]
This deserves group discussion but I vote for keeping red for conductive material, blue for resistive. If all agree we need to reverse the color bar.

**Comment by sdevriese** [comment]
I vote for that as well. 
The plots are in resistivity but the captions and text use conductivity.

**Comment by micmitch** [comment]
I agree that it would be nice to keep red for conductive and blue for resistive materials.

**Comment by sdevriese** [comment]
@fourndo changed so that red = cond, blue = res. Closing this issue.
