### ISSUE TITLE
 J (A/m 22) is electric currents

### ISSUE THREAD

**Issue by sdevriese** [ubcgif/em#268]
Should this be electric current density (as defined in maxwell fundamentals)?
@dccowan @sgkang

**Comment by sgkang** [comment]
Personally, I often call \vec{j} as electrical currents. 
Similarly, we call \vec{b} as magnetic field. What do you think about that @dougoldenburg ?

**Comment by sdevriese** [comment]
I can see that, given how we refer to \vec{b} as magnetic field sometimes but here, \vec{b} has been defined as magnetic flux density in the fundamental pages and \vec{h} as the magnetic field.
http://em.geosci.xyz/content/maxwell1_fundamentals/quick_guide_maxwell.html

Anyone else have thoughts on this? @lheagy @fourndo @yangdikun @thast @micmitch

**Comment by lheagy** [comment]
**j** is current density
**I** is current
