### ISSUE TITLE
DCR Survey: move stuff to Survey Design?

### ISSUE THREAD

**Issue by yangdikun** [ubcgif/em#269]
DCR Survey Design is under construction now. I read through DCR Survey and found there may be enough stuff to be transferred to DCR Survey Design, so (1) DCR doesn't look incomplete; (2) DCR Survey is not too long and overwhelming.

Just a though.

**Comment by sdevriese** [comment]
I think the plan was to leave it as is for now... I talked a bit about DCR survey design with Doug earlier this week and it'll eventually include some of the things I've done for my thesis.
