### ISSUE TITLE
Remove notebooks added in #278

### ISSUE THREAD

**Issue by lheagy** [ubcgif/em#279]
Notebooks should not be included in this repository, they can be included in em_examples if they have examples or generate figures specific to EM geosci, or included in SimPEG/tutorials if they are more of a demonstration of how to use a given code. 

In pr #278, 
- [ ] examples/geophysical_surveys/emi_tutorial/InducedCurrents.ipynb
- [ ] examples/maxwell2_fdem/emi_tutorial/Response function.ipynb
- [ ] examples/physical_properties/chargeability/ColeCole.ipynb
- [ ] examples/physical_properties/electrical_conductivity/ConductivityGenFigs.ipynb
- [ ] examples/physical_properties/electrical_conductivity/DCcurrent.ipynb

by the titles, it sounds like most of these would be well suited for inclusion in em_examples, @sgkang, I will let you decide

**Comment by sgkang** [comment]
removed ...
