### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by lheagy** [ubcgif/em#309]
https://github.com/ubcgif/em_examples/blob/master/notebooks/maxwell1_fundamentals/Magnetic_Dipole_Harmonic.ipynb no longer exists, hence this failure: https://travis-ci.org/ubcgif/em/builds/163201456. @sgkang : can you point @thast to the moved / updated notebook? Thanks!

**Comment by thast** [comment]
#310

**Comment by thast** [comment]
(need to add the Binders badge, just notice it is missing)

**Comment by lheagy** [comment]
closed with #310
