### ISSUE TITLE
Dipoles 

### ISSUE THREAD

**Issue by lheagy** [ubcgif/em#313]
@dccowan , @sgkang : could you provide the link to the google doc you are working on and a summary of your game plan here. Thanks!

**Comment by sgkang** [comment]
Links for 
- Harmonic Electric Dipole: https://docs.google.com/document/d/1JVSMA5u6ygKHmpF7qcNz6K0pm4x2gJrlGa3gLWdnzL4/edit?usp=sharing
- Harmonic Magnetic Dipole: https://drive.google.com/open?id=18K_vpXjw_d9nQwPp3_aJ5JZn_yMkj1h8JC4RvEXU1S8
- Transient Electric Dipole: https://drive.google.com/open?id=1v4AVL81fIS4wdgqRnRZfyPglXwApGOe08_K9s61C0aE
- Transient Magnetic Dipole: https://drive.google.com/open?id=1GlznRI__2l14b6NiWQL-h_ccPNQI0U4PCS0e5M4X598

**Comment by sgkang** [comment]
Restructuring Dipole (First use harmonic electric dipole as an example)
- [ ] Intro. page
   - Remove "What is it"
   - Purpose statement
   - Bit of story line (crosshole EM survey using vertical electric dipole)
   - Put thumb nail images 
   - Overview of what will be treated

- [ ] Analytic solutions
   - Merge “Vector potential” to here

- [ ] Asymptotic

- [ ] Field
   - Start from DC then to EM (but make it simple)
   - Visualize the fields (E, H)
   - Bit of sensitivity analyses
      - e.g. DC regime (dependent upon sigma)
      - Sigma (Use permeability for MD)
   - Frequency variations

- [ ] Harmonic Dipole widget
     - Introduce an widget and some guiding questions:    
     - Link for google doc: https://docs.google.com/document/d/1JVSMA5u6ygKHmpF7qcNz6K0pm4x2gJrlGa3gLWdnzL4/edit?usp=sharing
