### ISSUE TITLE
Plane waves

### ISSUE THREAD

**Issue by sgkang** [ubcgif/em#314]
Restructuring Plane wave (first frequency domain, then time domain)
- [x] Intro. page
  - Purpose statement
  - Bit of story line (Infinite current sheet, propagating downward to depth)
  - Put thumb nail images 
  - Overview of what will be treated
- [x] Analytic solutions
  -  Wavenumber
  -  Velocity (dispersive)
  -  Skin depth
  -  Polarization ellipse
- [x] Field
  - Start from DC then to EM (but make it simple)
  - Visualize the fields (E, H)
  - Bit of sensitivity analyses
    - e.g. DC regime (dependent upon sigma)
    - Sigma (Use permeability for MD)
  - Frequency variations
- [x] Harmonic Plane widget
  - Introduce an widget and some guiding questions:  

We want to be parallel with Dipole see issue #313 
Any thoughts? @dougoldenburg, @lheagy, @sdevriese ?

**Comment by lheagy** [comment]
I think this sounds good! I like the re-organization of grouping by source type, then breaking into frequency / time domain after that. To be sure we are all on the same page, here is a sketch of the file structure I would envision follows from this: (directories are bold, files are not) 

- **Maxwells_Equations_in_Homogeneous_Media/**
    - index.rst
    - **Plane_Waves/**
       - index.rst
       - **Frequency_Domain/**
            - index.rst
            - analytic_solution.rst
            - asymptotics.rst
            - fields.rst
            - app.rst (or "simulation", or "explore") 
       - **Time_Domain/**
            - index.rst
            - analytic_solution.rst
            - asymptotics.rst
            - fields.rst
            - app.rst (or "simulation", or "explore") 
    - **Dipole_Sources/** (structure being addressed in #315) 
 
@sgkang, @dccowan : is this what you had in mind?

**Comment by lheagy** [comment]
closed with #323, further re-organization is discussed in #346
