### ISSUE TITLE
Restructuring of Maxwells in Homogeneous Media

### ISSUE THREAD

**Issue by dccowan** [ubcgif/em#315]
I have a proposition for improving the current structure of content within Maxwell's equation in homogeneous media. I would like to meet as soon as possible to discuss. It is important because the content in each page must be written in the right context.

[Maxwell Homogeneous Media New Structure.docx](https://github.com/ubcgif/em/files/503994/Maxwell.Homogeneous.Media.New.Structure.docx)

**Comment by lheagy** [comment]
@dccowan : I have put this content in a google doc so that we can comment on it: https://docs.google.com/document/d/1WpnpOMhzODEPj-wbs9VnBOh_kH0Px9-ZTaLhUObxyM0/edit?usp=sharing

**Comment by lheagy** [comment]
The google doc is available for comment here: https://docs.google.com/document/d/1qx5cpgXttz0JdHSBTKF3VkdxcgU_MKA9xof6M1G4ZBY/edit?ts=57eef57d
