### ISSUE TITLE
Physical Properties: Magnetic Permeability References 

### ISSUE THREAD

**Issue by lheagy** [ubcgif/em#334]
References in the [magnetic permeability section](http://em.geosci.xyz/content/physical_properties/magnetic_permeability/index.html) need to be added to the [references.bib](https://github.com/ubcgif/em/blob/master/content/references.bib) and cited using `:cite:`. For an example, take a look at the [Mt. Isa Setup](https://github.com/ubcgif/em/blob/master/content/case_histories/mt_isa/setup.rst)

**Comment by dccowan** [comment]
Fixed links, references etc...
