### ISSUE TITLE
Maxwell1 Fundamentals: Action items required

### ISSUE THREAD

**Issue by sgkang** [ubcgif/em#341]
Similar ideas are mentioned in Issue: #297

Refactoring general structure of this section is crucial, and having action items will motivate people to jump on, and start fill-in those items.
### Maxwell's equations in homogeneous media

This is the main section for the Maxwell I: Fundamentals, and needs some restructuring:
- [ ] Re-structuring 
- [ ] Clear demonstration of the purpose statement
    (But not too many purpose statements (?) )
- [ ] Upon those purpose statement, suggesting action items
### Other sections:

Clarify what do we want to achieve from below sections ("purpose"), or merge with the previous one
- [ ] Quick Guide to Maxwell’s equations
- [ ] Solving Maxwell’s equations
- [ ] Looking for more?

**Comment by lheagy** [comment]
A tentative layout has been proposed in #346. @sgkang, @dccowan: if you could take a look at #346, your thoughts would be much appreciated!
