### ISSUE TITLE
html version issue

### ISSUE THREAD

**Issue by dccowan** [ubcgif/em#344]
I am using Windows 10, and did install 
`pip install html`

It does not have method called `html.escape()`, which makes problem for me
to compile em geosci. 

For temporary fix, we could try 

if sys.platform == "win32":
    pass
else:
    from _ext import (make_contributorslist)
    make_contributorslist()

from _ext import (
    make_formula_sheet, make_case_histories,
    checkDependencies, supress_nonlocal_image_warn
    )

make_formula_sheet()
make_case_histories()
supress_nonlocal_image_warn()

But, not sure this is a way to go... 

Any ideas? @lheagy ?

**Comment by lheagy** [comment]
@dccowan : I would prefer not to put system-specific patches in. It is possible that you do not have the correct version of anaconda installed. Please ensure that you have anaconda installed for 32 bit windows.

**Comment by sgkang** [comment]
Hey @dccowan do you still have this issue?
