### ISSUE TITLE
Question tag

### ISSUE THREAD

**Issue by sgkang** [ubcgif/em#350]
Putting some guiding questions seems helpful. Can we make question tag? similar to purpose?
Where do I need to look for making this type of custom tag? @lheagy

**Comment by lheagy** [comment]
Great idea! checkout [purpose.py](https://github.com/ubcgif/em/blob/master/_ext/purpose.py) in _ext. The style of the box is set in [theme_overrides.css](https://github.com/ubcgif/em/blob/master/_static/css/theme_overrides.css)

**Comment by sgkang** [comment]
Ha. sounds good @lheagy. Can I use .. yellow? kk

**Comment by lheagy** [comment]
as long as it is a nice yellow :)

**Comment by sgkang** [comment]
![screenshot from 2016-11-14 14 22 44](https://cloud.githubusercontent.com/assets/6054371/20285290/e0ecd66c-aa75-11e6-99b0-5abaecf5dd74.png)

**Comment by sgkang** [comment]
See #351
