### ISSUE TITLE
dc resistivity - physics 

### ISSUE THREAD

**Issue by lheagy** [ubcgif/em#398]
http://em.geosci.xyz/content/geophysical_surveys/dcr/physics.html

Figure 115 doesn't match the movie below. The spheres should be moved down 25m and preferably plotted down to 200m for consistency 

![image](https://cloud.githubusercontent.com/assets/6361812/21331435/41caec48-c5f7-11e6-8cbf-4ed44714d840.png)

**Comment by fourndo** [comment]
There must be a reason why we moved them up for the inversion.
I can give it a try at 50
