### ISSUE TITLE
We need reference bank ...

### ISSUE THREAD

**Issue by dccowan** [ubcgif/em#4]

**Comment by lheagy** [comment]
This will be easier soon! http://build-me-the-docs-please.readthedocs.org/en/latest/Using_Sphinx/UsingBibTeXCitationsInSphinx.html right now, this is a really young package, but we can test it out

**Comment by lheagy** [comment]
It looks like using: https://sphinxcontrib-bibtex.readthedocs.org/en/latest/usage.html could be a good option. Citations are then ``:cite:`citekey` ``. It doesn't yet have a nice author, year inline citation: it uses the author's last name and year mushed together (it would use [WH88] for Ward & Hohmann, but it can be customized). I am giving it a try on the "citation" branch.

**Comment by lheagy** [comment]
closed with #50
