### ISSUE TITLE
image for Aspen Case History

### ISSUE THREAD

**Issue by lheagy** [ubcgif/em#416]
The index page for the aspen case history (http://em.geosci.xyz/content/case_histories/aspen/index.html) currently does not have an image. @sdevriese is there a representative one that could be added? (can be a repeat) 

Perhaps this one (http://em.geosci.xyz/_images/FormationMM1.png):

![image](https://cloud.githubusercontent.com/assets/6361812/21650663/ee14d3de-d262-11e6-9ff1-5ab91bb8dc7f.png)

**Comment by sdevriese** [comment]
PR #417
