### ISSUE TITLE
Adding show / hide options (?)

### ISSUE THREAD

**Issue by sgkang** [ubcgif/em#56]
I guess this will be a useful for making concise documents.

http://stackoverflow.com/questions/2454577/sphinx-restructuredtext-show-hide-code-snippets

**Comment by lheagy** [comment]
nice, that is cool! We should try to make an example!?

**Comment by lheagy** [comment]
Right now, this is beyond the scope of the site (and how we are currently writing), so I am going to close this, but we can keep it in mind!
