### ISSUE TITLE
Notation for integrals

### ISSUE THREAD

**Issue by lheagy** [ubcgif/em#6]
When integrating over a Volume, Surface or Line, what do we want to use as symbols?

- V, S, C?

**Comment by thast** [comment]
To be consistent with Ward and Hohmann, I would choose these notations:
Volume: V and dv
Surface: S and ds
Line: C and dl

It would also be good to use the closed intergral notation ( \oint_ ) when needed (particularly to distinguish the cases where a closed surface is required)

**Comment by dccowan** [comment]
That works for me. Thibaut's convention is what I am used to. I also like
the \oint command in latex for integration over a closed path.

**Comment by lheagy** [comment]
Sounds good to me! If there are no objections, then 3 is a majority??
