### ISSUE TITLE
move code and examples

### ISSUE THREAD

**Issue by lheagy** [ubcgif/em#61]
the repo https://github.com/ubcgif/em_examples has been created to hold notebook examples. This is hooked up with [binders](http://mybinder.org) so that the examples can be run on the web without requiring python or dependencies be installed. 
- [x] migrate code to em_examples repo
- [x] integrate examples with SimPEG examples
- [x] allow site to compile locally without running all of the examples (if statement in the sphinx build)

**Comment by lheagy** [comment]
the codes that need to be moved are:

- [ ] electrostatic sphere @thast 
- [ ] effects of topography @sgkang

**Comment by lheagy** [comment]
@thast, can these be moved to em_examples? (or have they been moved?).

**Comment by thast** [comment]
@lheagy : electrostatic sphere was moved to EM_examples and is up running with binders.
What I do see is that there is still a folder "examples" at the root (EM/examples). This folder is not needed anymore and can be removed (I create the PR for it).

**Comment by thast** [comment]
I do not know about effects of topography (not in EM/examples anyway). @sgkang ?

**Comment by thast** [comment]
#276

**Comment by lheagy** [comment]
closed with #276
