### ISSUE TITLE
Wavenumber page not in toctree

### ISSUE THREAD

**Issue by lheagy** [ubcgif/em#71]
#67 introduced the wavenumber page (wave_number.rst) inside of /Users/lindseyjh/git/geosci/em/content/maxwell1_fundamentals/physical_principles/maxwells_equations_in_homogeneous_media that is not currently in a table of contents tree. 

The content should be included, as relevant, to the wave propagation in free space (topic of the pull request #58) @sdevriese, you may want to take a look at this file and see if the content @micmitch generated meshes with what you have done

**Comment by lheagy** [comment]
@sdevriese, @micmitch : has this been resolved?

**Comment by sdevriese** [comment]
The things Mike wrote were in the pages I created.

**Comment by dougoldenburg** [comment]
Hi Sarah,

                Can you drop up?

Thanks

Doug
